/**
 * @file vindstryka_lcd.h
 * @brief Driver for the Vindstryka LCD using HT1621 controller
 * @author Ed Holmes (ed.holmes(at)me.com)
 * @date 2025-11-09
 * @copyright Copyright (c) 2025 Ed Holmes
 *
 * Library contains functions to initialize, update, and control the Vindstryka LCD.
 *
 * SPDX-License-Identifier: MIT
 *
 */

#ifndef VINDSTRYKA_LCD_H_
#define VINDSTRYKA_LCD_H_

#include <stdint.h>

//! Number of digits on the Vindstryka LCD
#define VINDSTRYKA_LCD_NUM_DIGITS 9

enum VINSTRYKA_LCD_ICON
{
    // Top row icons
    VINDSTRYKA_LCD_ICON_ROOM = 0,
    VINDSTRYKA_LCD_ICON_WINDOW,
    VINDSTRYKA_LCD_ICON_HOUSE,
    VINDSTRYKA_LCD_ICON_TREES,
    VINDSTRYKA_LCD_ICON_WRENCH,
    VINDSTRYKA_LCD_ICON_ADD_PURIFIER,
    VINDSTRYKA_LCD_ICON_PURIFIER,
    VINDSTRYKA_LCD_ICON_LINKED,
    VINDSTRYKA_LCD_ICON_TOP_LEFT_UNDERLINE,
    VINDSTRYKA_LCD_ICON_TOP_UNDERLINE,
    VINDSTRYKA_LCD_ICON_PM25,

    // Traffic Light arrows
    VINDSTRYKA_LCD_ICON_TL_RED,
    VINDSTRYKA_LCD_ICON_TL_RED_YELLOW,
    VINDSTRYKA_LCD_ICON_TL_YELLOW,
    VINDSTRYKA_LCD_ICON_TL_YELLOW_GREEN,
    VINDSTRYKA_LCD_ICON_TL_GREEN,

    // Brightness icons
    VINDSTRYKA_LCD_ICON_BRIGHTNESS,
    VINDSTRYKA_LCD_ICON_BRIGHTNESS_LEVEL_1,
    VINDSTRYKA_LCD_ICON_BRIGHTNESS_LEVEL_2,
    VINDSTRYKA_LCD_ICON_BRIGHTNESS_LEVEL_3,
    VINDSTRYKA_LCD_ICON_AUTO_OFF,

    VINDSTRYKA_LCD_ICON_THERMOMETER,
    VINDSTRYKA_LCD_ICON_FARENHEIT,
    VINDSTRYKA_LCD_ICON_FARENHEIT_ARROW,
    VINDSTRYKA_LCD_ICON_CELSIUS,
    VINDSTRYKA_LCD_ICON_CELSIUS_ARROW,
    VINDSTRYKA_LCD_ICON_DROPLET,
    VINDSTRYKA_LCD_ICON_PERCENTAGE,

    // Bottom row icons
    VINDSTRYKA_LCD_ICON_TVOC,
    VINDSTRYKA_LCD_ICON_FLOWER,
    VINDSTRYKA_LCD_ICON_ARROW_UP,
    VINDSTRYKA_LCD_ICON_ARROW_DOWN,
    VINDSTRYKA_LCD_ICON_ARROW_RIGHT,

    VINDSTRYKA_LCD_ICON_LIST_ARROW_1,
    VINDSTRYKA_LCD_ICON_LIST_ARROW_2,
    VINDSTRYKA_LCD_ICON_LIST_ARROW_3,
    VINDSTRYKA_LCD_ICON_LIST,

    VINDSTRYKA_LCD_NUM_ICONS
};

// High-level functions
void VINDSTRYKA_LCD_Init(void);
void VINDSTRYKA_LCD_SetDigit(uint8_t digit, uint8_t value);
void VINDSTRYKA_LCD_SetIcon(enum VINSTRYKA_LCD_ICON icon, uint8_t state);
void VINDSTRYKA_LCD_Update(void);
void VINDSTRYKA_LCD_Clear(void);

#endif